services:
  spring:
    container_name: sweldox-server
    image: ghcr.io/iodsky/sweldox-api:latest
    restart: always
    ports:
      - 8001:8001
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sweldox.rule=Host(`sweldox.iodsky.com`)"
      - "traefik.http.routers.sweldox.entrypoints=websecure"
      - "traefik.http.routers.sweldox.tls.certresolver=myresolver"
      - "traefik.http.services.sweldox.loadbalancer.server.port=8001"
    networks:
      - sweldox-network
      - traefik

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 1800
      WATCHTOWER_INCLUDE_RESTARTING: "true"
    command: --cleanup spring
    networks:
      - sweldox-network

volumes:
  postgres-data:

networks:
  sweldox-network:
  traefik:
    external: true