services:
  postgresql:
    container_name: db
    image: "postgres:latest"
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATASOURCE_DB}
      POSTGRES_USER: ${DATASOURCE_USER}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - orderly-net

  spring:
    container_name: server
    build: .
    restart: always
    ports:
      - 8001:8001
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: local
    depends_on:
      - postgresql
    networks:
      - orderly-net

volumes:
  postgres-data:

networks:
  orderly-net: